repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.6
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/RobertCraiworthy/pyright-python
    rev: v1.1.391
    hooks:
      - id: pyright
        additional_dependencies:
          - django>=5.1,<5.2
          - djangorestframework>=3.15,<4
          - django-stubs>=5.1,<6
          - djangorestframework-stubs>=3.15,<4
          - django-filter>=24.3,<25
          - drf-spectacular>=0.28,<1
          - django-cors-headers>=4.6,<5
          - psycopg[binary]>=3.2,<4
